name: meal_tracking_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  get_it: ^8.0.3
  conditional_builder_null_safety: ^0.0.6
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  sqflite: ^2.4.1
  image_picker: ^1.1.2
  dio: ^5.8.0+1
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
